// src/db/schema/user-schema.ts
//
// The user table and its relations. The `users` definition itself comes from
// `auth-schema.ts` (generated by the better-auth CLI); we re-export it here so
// the rest of the code imports from one consistent place.

import { relations } from "drizzle-orm/relations";
import { users } from "./auth-schema";
import { questions } from "./question-schema";

export { users };
export type { User } from "./auth-schema";

export const userRelations = relations(users, ({ many }) => ({
  questions: many(questions),
}));
